spring:
    security:
        oauth2:
            client:
                registration:
                    google:
                        client-id: ${GOOGLE_CLIENT_ID}
                        client-secret: ${GOOGLE_CLIENT_SECRET}
                        scope:
                            - openid
                            - profile
                            - email
                    discord:
                        client-id: ${DISCORD_CLIENT_ID}
                        client-secret: ${DISCORD_CLIENT_SECRET}
                        client-authentication-method: client_secret_post
                        authorization-grant-type: authorization_code
                        scope:
                            - identify
                            - email
                provider:
                    google:
                        issuer-uri: https://accounts.google.com
                    discord:
                        authorization-uri: https://discord.com/api/oauth2/authorize
                        token-uri: https://discord.com/api/oauth2/token
                        user-info-uri: https://discord.com/api/users/@me
                        user-name-attribute: id
