services:
  db:
    image: postgres:15-alpine
    container_name: bits
    restart: always
    environment:
      POSTGRES_DB: bits
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: danilamasguapa
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d bits"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build: .
    container_name: bits-app
    restart: on-failure
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/bits
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: danilamasguapa
      SPRING_JPA_HIBERNATE_DDL_AUTO: create-drop
      SPRING_JPA_SHOW_SQL: "true"
      SPRING_SQL_INIT_MODE: never
      SPRING_JPA_DATABASE_PLATFORM: org.hibernate.dialect.PostgreSQLDialect

volumes:
  db-data: