services:
    db:
        image: postgres:15-alpine
        container_name: bits
        restart: unless-stopped
        environment:
            POSTGRES_DB: ${DB_NAME:-bits}
            POSTGRES_USER: ${DB_USER:-postgres}
            POSTGRES_PASSWORD: ${DB_PASSWORD:-danilamasguapa}
        volumes:
            - db-data:/var/lib/postgresql/data
        ports:
            - "5434:5432"
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U ${DB_USER:-postgres} -d ${DB_NAME:-bits}"]
            interval: 10s
            timeout: 5s
            retries: 5

    app:
        build: .
        container_name: bits-app
        restart: on-failure
        depends_on:
            db:
                condition: service_healthy
        ports:
            - "8080:8080"
        volumes:
            - ./dbinit:/app/sql
        environment:
            DB_URL: ${DB_URL}
            DB_USERNAME: ${DB_USER}
            DB_PASSWORD: ${DB_PASSWORD}
            SPRING_JPA_HIBERNATE_DDL_AUTO: update
            SPRING_JPA_SHOW_SQL: "true"
            SPRING_SQL_INIT_MODE: always
            SPRING_JPA_DEFER_DATASOURCE_INITIALIZATION: "true"
            SPRING_SQL_INIT_PLATFORM: postgresql
            SPRING_SQL_INIT_DATA_LOCATIONS: file:/app/sql/init.sql
            SPRING_JPA_DATABASE_PLATFORM: org.hibernate.dialect.PostgreSQLDialect
            JWT_SECRET: ${JWT_SECRET}

volumes:
    db-data:
