###
GET http://localhost:8080/api/v1/transactions
###
POST http://localhost:8081/api/v1/transactions
Content-Type: application/json

{
  "userId": "22222222-2222-2222-2222-222222222222",
  "details": [
    {
      "price": 25.0
    }
  ]
}

###
GET http://localhost:8081/api/v1/transactions
###


GET http://localhost:8081/api/v1/transactions/be10a759-d060-42a3-9cdb-555c37515200
###

GET http://localhost:8080/api/v1/transactions/user/22222222-2222-2222-2222-222222222222
###


GET http://localhost:8080/api/v1/transactions/be10a759-d060-42a3-9cdb-555c37515200/details
###